version: "3"
services:
  backend:
    image: juhisohane/spe-major-backend
    container_name: backendcontainer
    ports:
      - "9192:9192"
    networks:
      - debtly-network
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: databasecontainer
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Debtly
    volumes:
      - db:/var/lib/mysql
    networks:
      - debtly-network

  volumes:
    db: